<?php

	drupal_add_css(drupal_get_path('module','agency').'/media/css/jquery.dataTables.css');
	drupal_add_css(drupal_get_path('module','agency').'media/css/form.css');

	drupal_add_js(drupal_get_path('module', 'agency') . '/media/js/agency.js');
	drupal_add_js(drupal_get_path('module','agency').'/media/js/jquery.js');
	drupal_add_js(drupal_get_path('module','agency').'/media/js/jquery.dataTables.js');
	
function employee_menu() {

	
	$items = array();	
	
	$items['agency/search'] = array(
			'title' => t('Agency Search'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('agency_form'),
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);	
	$items['admin/agency'] = array(
			'title' => 'Agency',
			'description' =>  'Configure Agency settings.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('agency_admin'),
			'access arguments' => array('administer users'),
			'menu_name' => 'Agency Configuration',
	);

	return $items;
}

function agency_form() {
	try {
	
	$ch = curl_init();
		
		$headers = array(
				"Authorization: Bearer iOdEYtG1i70tHhVEHX5e1YqGBEsa",
				);		
		curl_setopt_array($ch, array(
		CURLOPT_RETURNTRANSFER => 1,
		CURLOPT_HTTPHEADER => $headers,
		CURLOPT_URL => "http://172.19.1.173:8285/agency/1.0/get_orglist?org_id=null"  //$agency_api . "?org_id=null"
		));
		$response = curl_exec($ch);
		curl_close($ch);
		
		$xml = preg_replace("/(<\/?)(\w+):([^>]*>)/", "$1$2$3", $response);
		$xml = simplexml_load_string($xml);		
		$json = json_encode($xml);
		$empArray = json_decode($json, true);
		
		
		if (count($empArray) > 0) {
			if(isset($empArray['agency'][0]))
			{
				$empArray = $empArray['agency'];
			}
		
		//My Requests
			if (count($empArray) > 0) {
				//$form['results_header'] = array('#markup' => t('<h2>Search Results</h2>'));
				$tableRows = '<h2>Search Results</h2><table cellpadding="0" cellspacing="0" border="0" class="dataTable" id="example" width="100%">
						<thead>		
						<th>Agency Name</th>
						<th>Agency Code</th>
						
						<th>Website</th>
						</thead>';
				foreach ($empArray as $empArrayItem){		
					
					$tableRows .= '<tr><td>' .$empArrayItem['title'] .'</td><td>' .$empArrayItem['abrv'] .'</td><td>' .($empArrayItem['link'] ? $empArrayItem['phone'] : '') .'</td><td style="display: ' . $isAuthorized . ';">' .($empArrayItem['email'] ? $empArrayItem['email'] : '') .'</td></tr>';
		
				}
				$tableRows .= '</table>';
				$form['results'] = array('#markup' => t($tableRows));
				session('results', $tableRows);
			}
			$form['FirstName']['#value'] = $firstname;
		}	
}
	catch (Exception $e)
	 {
		// Log the exception to watchdog.
		handle_exception($e);
	}
}

function Agency_admin() 
{
	try {
		$form = array();

		$form['Agencies'] = array(
				'#type' => 'textfield',
				'#title' => t('Angency API'),
				'#default_value' => variable_get('Employee_AgencyAPI', 'http://172.19.1.173:8285/agency/1.0/get_orglist'),
				'#description' => t("The API to load agencies."),
				'#required' => TRUE,
		);
		
		$form['Agency_Search'] = array(
				'#type' => 'textfield',
				'#title' => t('Agency List'),
				'#default_value' => variable_get('Agency_SearchAPI', 'http://172.19.1.173:8285/agency/1.0/get_orglist'),
				'#description' => t("API to Search Agencies"),
				'#required' => TRUE,
		);
		return system_settings_form($form);
	}
	catch (Exception $e) {
		// Log the exception to watchdog.
		handle_exception($e);
	}
}




