<?php
//googleMapLoad();
//drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAOqDgzd_mPTBbpYY8duQtJJLJZJ12ZuZI&sensor=true', 'external');
//drupal_add_js(drupal_get_path('module','geocoder').'/GoogleDynamicMap.js');


function azneighborhood_menu() {

	$items = array();	
	
	$items['myneighborhood'] = array(
			'title' => t('My Neighborhood'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('azneighborhood_form'),
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);

	$items['admin/myneighborhood'] = array(
			'title' => 'myneighborhood',
			'description' =>  'Configure azneighborhood settings.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('azneighborhood_admin'),
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function azneighborhood_form() {
	try {

			
		$form['html_markupIntial'] = array('#markup' => t('<table  border="0" cellspacing="0" background="#e3ecff"><tr><td>'));
		
		$form['Address'] = array(
				'#type' => 'textfield',
				'#title' => t('Address'),
				'#size' => 40,
				'#required' => FALSE,
		);
		
		$form['html_markup0'] = array('#markup' => t('</td><td style="border:{0px,0px,0px,0px}">'));
		
		$form['Zipcode'] = array(
				'#type' => 'textfield',
				'#title' => t('Zip code'),
				'#size' => 30,
				'#required' => FALSE,
		);
		
		$form['html_markup1'] = array('#markup' => t('</td><td style="border:{0px,0px,0px,0px}">'));
		
		$form['Submit'] = array(
				'#type' => 'submit',
			'#value' => t('Search'),
			'#submit' => array('azneighborhood_search'),
		);
		
		$form['html_markup56'] = array('#markup' => t('</td></tr></table>'));		
		
		
		$form['results'] = array('#markup' => t(session('results')));
		
		session('results', "");

		return $form;
	}
	catch (Exception $e) {
		// Log the exception to watchdog.
		handle_exception($e);
	}

}


function azneighborhood_search($form, $form_state) {

	try{
		
		//Clear session		
		session('results', "");
		
		$Address=$form_state['values']['Address'];
		$Zipcode=$form_state['values']['Zipcode'];
		
		if($Address == "")
		{
			$Address = "null";			
		}
		if($Zipcode == "")
		{
			$Zipcode = "null";
		}

		// Replacing the empty strings with %20
		
		$replace_string = '%20';
		$Address = str_replace(' ',$replace_string, $Address);
		
		
		// Filter - Auth key		
		// $Authkey = 'e594d39750e16ffa2eaffdf4899dfbbe';
		
		// Getting the values from configuration
		// Auth Key
		 $authkey = variable_get('azneighborhood_Authkey');
		// Access Token 
		$accesstoken = variable_get('azneighborhood_APIAccesToken');
		// APi URL
		$apiurl = variable_get('azneighborhood_APIcall'); 

		$ch = curl_init();
		$headers = array(
				"Authorization : Bearer $accesstoken",
		);
				
		curl_setopt_array($ch, array(
		CURLOPT_RETURNTRANSFER => 1,
		CURLOPT_HTTPHEADER => $headers,		
		// workstation
		CURLOPT_URL =>$apiurl.'?address='.$Address.'&zipcode='.$Zipcode.'&authkey='.$authkey
		// QA links
		//CURLOPT_URL =>'http://172.19.2.216:8285/geocoder/1.0.0/get_info.php?address='.$Address.'&zipcode='.$Zipcode.'&authkey='.$Authkey
		// Dev links
		//CURLOPT_URL =>'http://172.19.2.216:8285/geocoder/1.0.0/get_info.php?address='.$Address.'&zipcode='.$Zipcode.'&authkey='.$Authkey
		));
		
		$response = curl_exec($ch);
		curl_close($ch);
		
		$xml = preg_replace("/(<\/?)(\w+):([^>]*>)/", "$1$2$3", $response);
		$xml = simplexml_load_string($xml);
		$json = json_encode($xml);
		$empArray = json_decode($json, true);
		
		$latitude = $xml->geo_info->latitude;
		$longitude = $xml->geo_info->longitude;
		
		$latlong_values = $latitude.','.$longitude;
		
		$googlemapurl =	'http://maps.googleapis.com/maps/api/staticmap?center='.$latlong_values.'&markers=size:med|'.$latlong_values.'&zoom=12&size=618x400&scale=1&key=AIzaSyAOqDgzd_mPTBbpYY8duQtJJLJZJ12ZuZI&sensor=false';
			
		$results_ = 
		'<div id="map-canvas" class="map-container">
			 	<ul>
					<li><img src='.$googlemapurl.'></img></li>
				</ul> 
		</div>
				<div class="field-container">								
				<ul>
					<li><h3 class="left">Standardized Address</h3></li>
					<li><h5 class="heading">'.$xml->address_info->street.',<br/>'.$xml->address_info->city.',<br/>'.$xml->address_info->state.'</h5></p></li>
				</ul>
				<ul>
                    <li><h3 class="left">Geolocation Codes</h3></li>
                    <li><h5 class="heading">'. 'latitude:'.'</h5><p> '.$xml->geo_info->latitude.'</p></li>
					<li><h5 class="heading">'.'longitude:'.'</h5><p> '.$xml->geo_info->longitude.'</p></li>
                </ul> 
				<ul id="combo">
                    <li><h3 class="left">Zip Codes & Mail Delivery</h3></li>
                    <li><h5 class="heading">'.'Zip 5:'.'</h5><p> '.$xml->address_info->zip5.'</p></li>
					<li><h5 class="heading">'.'Zip 9:'.'</h5><p> '.$xml->zipcode_carrierroute->zip9->zip9_value.'</p></li>
					<li><h5 class="heading">'.'Carrier Route:'.'</h5><p> '.$xml->zipcode_carrierroute->carrier_route->carrier_route_value.'</p></li>
                </ul>  
				<ul id="combo">
                    <li><h3 class="left">Political Jurisdictions & Elected Officials</h3></li>
                    <li><h5 class="heading">'.'National Senate: '.'</h5><p> '.$xml->jurisdictions_info->congressional_legislators->official_state.'</p></li>
                    <li><p class="result">'.$xml->jurisdictions_info->congressional_legislators->national_senator->national_senator_1.'</p></li>
                    <li><p class="result">'. $xml->jurisdictions_info->congressional_legislators->national_senator->national_senator_2.'</p></li>
                    <li></li>
                    <li><h5 class="heading">Congressional District:</h5></li>
                    <li><p class="result">'.$xml->jurisdictions_info->congressional_legislators->congressional_district->congressional_district_name.'  ('.$xml->jurisdictions_info->congressional_legislators->congressional_district_id->congressional_district_id_value.')'.'</p></li>                  
                    <li><p class="result">'.$xml->jurisdictions_info->congressional_legislators->house_of_representative->representative_1.'</p></li>
					<li></li>
                    <li><h5 class="heading">State Executives:</h5></li>
                    <li><p class="result">Governor:'.$xml->jurisdictions_info->state_legislation->state_executives->governor.'</p></li>  
                    <li></li>                
					<li><h5 class="heading">State Upper House:</h5></li>
                    <li><p class="result">'.$xml->jurisdictions_info->state_legislation->state_upper_house_district_1->state_upper_house_district_1_name.'  ('. $xml->jurisdictions_info->state_legislation->state_upper_house_district_1_id->state_upper_house_district_1_id_value.')'.'</p></li>  
					<li><p class="result">'.$xml->jurisdictions_info->state_legislation->state_upper_house_district_1_state_upper_house_member->state_upper_house_district_1_state_upper_house_member_1.'</p></li>
					<li></li> 
					<li><h5 class="heading">State Lower House:</h5></li>
                    <li><p class="result">'.$xml->jurisdictions_info->state_legislation->state_lower_house_district_1->state_lower_house_district_1_name .'  ('.$xml->jurisdictions_info->state_legislation->state_lower_house_district_1_id->state_lower_house_district_1_id_value.')'.'</p></li>
                    <li><p class="result">'.$xml->jurisdictions_info->state_legislation->state_lower_house_district_1_state_lower_house_member->state_lower_house_district_1_state_lower_house_member_1.'</p></li>
					<li><p class="result">'.$xml->jurisdictions_info->state_legislation->state_lower_house_district_1_state_lower_house_member->state_lower_house_district_1_state_lower_house_member_2.'</p></li>
					<li></li> 
					<li><h5 class="heading">'.'County: '.'</h5><p> '.$xml->jurisdictions_info->county->county_name.'</p></li>
					<li></li> 
					<li><h5 class="heading">'.'County Subdivision: '.'</h5><p>'.$xml->jurisdictions_info->county_subdivision->county_subdivision_name.'</p></li>
					<li></li> 
					<li><h5 class="heading">'.'Municipal :'.'</h5><p>'. $xml->jurisdictions_info->municipal->municipal_name.'</p></li>	
					<li></li>				
					<li><h5 class="heading">'.'Voting Precinct :'.'</h5><p>'. $xml->jurisdictions_info->voting_district->voting_district_name.'</p></li>
					<li></li>
					<li><h5 class="heading">School Districts:</h5><p></p></li>
					<li><h5 class="heading">'.'Primary :'.'</h5><p>'.$xml->jurisdictions_info->school_districts->primary_school_district.'</p></li>
					<li><h5 class="heading">'.'Secondary :'.'</h5><p>'. $xml->jurisdictions_info->school_districts->secondary_school_district.'</p></li>
					<li><h5 class="heading">'.'Unified : '.'</h5><p>'. $xml->jurisdictions_info->school_districts->unified_school_district.'</p></li>
				</ul>
				<ul id="combo">
					<li><h3 class="left">Census Statistics</p></li>
                    <li><h5 class="heading">'.'Census Tract: '.'</h5><p>'. $xml->census_info->census_tract->census_tract_value.'</p></li>
					<li><h5 class="heading">'.'Block Group: '.'</h5><p>'. $xml->census_info->block_group->block_group_name.'</p></li>
					<li><h5 class="heading">'.'Census Block:'.'</h5><p>'. $xml->census_info->census_2010_block->census_2010_block_value.'</p></li>
					<li><h5 class="heading">'.'Census Block:'.'</h5><p>'. $xml->census_info->census_2000_block->census_2000_block_value.'</p></li>
					<li><h5 class="heading">'.'MSA :'.'</h5><p>'. $xml->census_info->msa->msa_name.'</p></li>
					<li><h5 class="heading">'.'Urban or Rural Area :'.'</h5><p>'. $xml->census_info->urban_or_rural_area->urban_area_name.'</p></li>												
                </ul>        	
		</div>';
		
		/* require_once(drupal_get_path('module','geocode').'/includes/geocode.inc');
		$geocode = new geocode_google();
		$options = '&key=' . variable_get('googlemap_api_key', ''); //take the gmap key
		$options .=  '&sensor=false';
		$googleQuery = $assigned['city'].'+Switzerland';
		$ret = $geocode->geocode($googleQuery,$options); */

		session('results', $results_);
	}
	
	catch (Exception $e) {
		// Log the exception to watchdog.
		handle_exception($e);
	}
}


function googleMapLoad() {

	// Javascript values
	drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAOqDgzd_mPTBbpYY8duQtJJLJZJ12ZuZI&sensor=true', 'external');
	drupal_add_js(drupal_get_path('module','azneighborhood').'/GoogleDynamicMap.js');
	
}


function azneighborhood_admin(){
	
	try {
		
		$form = array();
		
		$form['azneighborhood_Authkey'] = array(
				'#type' => 'textfield',
				'#title' => t('Authentication Key'),
				'#default_value' => variable_get('azneighborhood_Authkey', 'e594d39750e16ffa2eaffdf4899dfbbe'),
				'#description' => t("API Authentication Key"),
				'#required' => TRUE,
		);
		
		$form['azneighborhood_APIAccesToken'] = array(
				'#type' => 'textfield',
				'#title' => t('API Access Token'),
				'#default_value' => variable_get('azneighborhood_APIAccesToken', 'iOdEYtG1i70tHhVEHX5e1YqGBEsa'),
				'#description' => t("API Access Token"),
				'#required' => TRUE,
		);
		
		$form['azneighborhood_APIcall'] = array(
				'#type' => 'textfield',
				'#title' => t('API Call'),
				'#default_value' => variable_get('azneighborhood_APIcall', 'http://172.19.2.216:8285/geocoder/1.0.0/get_info.php'),
				'#description' => t("API URL"),
				'#required' => TRUE,
		);
		
		
		return system_settings_form($form);
	}
	
	catch (Exception $e) {
		// Log the exception to watchdog.
		handle_exception($e);
	}
	
	
}


function session($key, $value = NULL) {
	try {
		static $storage;
		if ($value != NULL) {
			$storage[$key] = $value ;
			$_SESSION['nr'][$key] = $value ;   // I put 'lists' in case some other module uses 'type' in $_SESSION
		}
		else if (empty($storage[$key]) && isset($_SESSION['nr'][$key])) {
			$storage[$key] = $_SESSION['nr'][$key];
		}
		return $storage[$key];
	}
	catch (Exception $e) {
		// Log the exception to watchdog.
		handle_exception($e);
	}
}




